# Generated by Django 4.0.4 on 2022-04-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonmore',
            name='when',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
