# Generated by Django 4.0.4 on 2022-04-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hackathonmore_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonmore',
            name='when',
        ),
    ]
